# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ProximalAlgorithms")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
#  - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("ProximalAlgorithms")); include(joinpath("docs", "make.jl"))'
